// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://retpadayxnzhmckvphvf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJldHBhZGF5eG56aG1ja3ZwaHZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczODI0NDksImV4cCI6MjA3Mjk1ODQ0OX0.FQ4cSfnXH6QAZwXqlw76Hkn82RFO9_RwqCrLs0SVjVA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});